// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokMultilink, StoryblokRichtext } from '../storyblok.d.ts';
export interface BlogPost {
  author: number | string;
  category?: (number | string)[];
  headline: string;
  image: StoryblokAsset;
  introText: StoryblokRichtext;
  copy: StoryblokRichtext;
  component: "blogPost";
  _uid: string;
  [k: string]: unknown;
}

export interface BlogPostList {
  headline: string;
  linkText: string;
  component: "blogPostList";
  _uid: string;
  [k: string]: unknown;
}

export interface CareerItem {
  period?: string;
  title?: string;
  company?: string;
  description?: string;
  component: "careerItem";
  _uid: string;
  [k: string]: unknown;
}

export interface CareerTimeline {
  title: string;
  description?: string;
  items?: CareerItem[];
  component: "careerTimeline";
  _uid: string;
  [k: string]: unknown;
}

export interface CollapsibleItem {
  title?: string;
  description?: string;
  component: "collapsibleItem";
  _uid: string;
  [k: string]: unknown;
}

export interface CollapsibleItemList {
  title?: string;
  description?: string;
  items?: CollapsibleItem[];
  component: "collapsibleItemList";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactForm {
  id: string;
  title: string;
  description?: StoryblokRichtext;
  submit_button_text?: string;
  background?: "" | "base-100" | "base-200" | "base-300";
  max_width?: "" | "2xl" | "3xl" | "4xl";
  component: "contactForm";
  _uid: string;
  [k: string]: unknown;
}

export interface FeatureItem {
  number?: string;
  title?: string;
  description?: string;
  component: "featureItem";
  _uid: string;
  [k: string]: unknown;
}

export interface FeatureList {
  title?: string;
  description?: string;
  features?: FeatureItem[];
  links?: Link[];
  component: "featureList";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  copyright?: string;
  legalLinks?: NavLink[];
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  navLinks?: NavLink[];
  ctaButton?: NavLink[];
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroImage {
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  links?: Link[];
  component: "heroImage";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroSection {
  title?: string;
  description?: string;
  links?: Link[];
  component: "heroSection";
  _uid: string;
  [k: string]: unknown;
}

export interface InfoCard {
  emoji?: string;
  title?: string;
  description?: string;
  component: "infoCard";
  _uid: string;
  [k: string]: unknown;
}

export interface InfoCardList {
  title?: string;
  description?: string;
  cards?: InfoCard[];
  component: "infoCardList";
  _uid: string;
  [k: string]: unknown;
}

export interface Intro {
  headline?: string;
  richtext?: StoryblokRichtext;
  blocks?: Link[];
  component: "intro";
  _uid: string;
  [k: string]: unknown;
}

export interface Link {
  text: string;
  url: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  variant: "" | "primary" | "secondary" | "accent" | "ghost" | "link";
  size: "" | "xs" | "sm" | "md" | "lg";
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface NavLink {
  url: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  text: string;
  isSmall?: boolean;
  component: "navLink";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | BlogPost
    | BlogPostList
    | CareerItem
    | CareerTimeline
    | CollapsibleItem
    | CollapsibleItemList
    | ContactForm
    | FeatureItem
    | FeatureList
    | Footer
    | Header
    | HeroImage
    | HeroSection
    | InfoCard
    | InfoCardList
    | Intro
    | Link
    | NavLink
    | Page
    | PricingCard
    | PricingCardFeature
    | PricingGrid
    | RichText
    | SeoPage
    | SocialMedia
    | SocialMediaList
    | TechStack
    | TechStackItem
    | TextBackground
  )[];
  title?: string;
  description?: string;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface PricingCard {
  badge_text?: string;
  title?: string;
  subtitle?: string;
  price?: string;
  price_suffix?: string;
  description?: string;
  highlighted?: boolean;
  features?: PricingCardFeature[];
  links?: Link[];
  component: "pricingCard";
  _uid: string;
  [k: string]: unknown;
}

export interface PricingCardFeature {
  text?: string;
  component: "pricingCardFeature";
  _uid: string;
  [k: string]: unknown;
}

export interface PricingGrid {
  title?: string;
  footer_text?: string;
  pricing_cards?: PricingCard[];
  component: "pricingGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface RichText {
  content: StoryblokRichtext;
  max_width?: "" | "2xl" | "3xl" | "4xl" | "5xl" | "6xl" | "7xl";
  background?: "" | "base-100" | "base-200" | "base-300";
  component: "richText";
  _uid: string;
  [k: string]: unknown;
}

export interface SeoPage {
  siteName?: string;
  ogImage?: StoryblokAsset;
  component: "seoPage";
  _uid: string;
  [k: string]: unknown;
}

export interface SocialMedia {
  text?: string;
  url?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "socialMedia";
  _uid: string;
  [k: string]: unknown;
}

export interface SocialMediaList {
  links?: SocialMedia[];
  component: "socialMediaList";
  _uid: string;
  [k: string]: unknown;
}

export interface TechStack {
  title?: string;
  description?: string;
  items?: TechStackItem[];
  component: "techStack";
  _uid: string;
  [k: string]: unknown;
}

export interface TechStackItem {
  name?: string;
  icon?: string;
  component: "techStackItem";
  _uid: string;
  [k: string]: unknown;
}

export interface TextBackground {
  isTitle?: boolean;
  copy: StoryblokRichtext;
  blocks?: Link[];
  component: "textBackground";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = BlogPost | Page | SeoPage;
