// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface Link {
  text: string;
  url: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Link | Page | SeoPage)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface SeoPage {
  siteName?: string;
  ogImage?: StoryblokAsset;
  component: "seoPage";
  _uid: string;
  [k: string]: unknown;
}
