// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface BlogPost {
  headline?: string;
  component: "blogPost";
  _uid: string;
  [k: string]: unknown;
}

export interface ClipPath {
  isTitle?: boolean;
  copy: StoryblokRichtext;
  blocks?: Link[];
  component: "clipPath";
  _uid: string;
  [k: string]: unknown;
}

export interface Link {
  text: string;
  url: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (BlogPost | ClipPath | Link | Page | SeoPage)[];
  title?: string;
  description?: string;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface SeoPage {
  siteName?: string;
  ogImage?: StoryblokAsset;
  component: "seoPage";
  _uid: string;
  [k: string]: unknown;
}
